### ISSUE TITLE
'get' 'responses' methods raise exceptions

### ISSUE THREAD

**Issue by wfspotz** [huffpostdata/python-pollster#10]
The following question slugs result in a `ValueError: Integer column has NA values in column 9` being raised when the strings are passed as the argument to `Api.questions_slug_poll_responses_clean_tsv_get(question_slug)`:

`00c -US-Trump-Donald-Favorable`
`00c -US-Sanders-Bernie-Favorable`
`00c -US-Cruz-Ted-Favorable`
`00c -US-Rubio-Marco-Favorable`
`00c -US-Republican-Party-Favorable`
`00c -US-Democratic-Party-Favorable`
`00c -US-Clinton-Hillary-Favorable`
`00c -Pres-44-Obama - Favorable Rating-National`

Just to make sure, I checked the following slugs, which returned cleanly:

`-US-Schumer-Chuck-Favorable`
`-US-Stein-Jill-Favorable`
`-US-Johnson-Gary-Favorable`
`-US-Tim-Kaine-favorable`
`-US-Pence-Mike-favorable`
`00c -US-O-Malley-Martin-Favorable`
`00c -US-Pataki-George-Favorable`
`00c -US-Graham-Lindsey-Favorable`
`00c -US-Jindal-Bobby-Favorable`
`00c -US-Gilmore-Jim-Favorable`
`00c -US-Chafee-Lincoln-Favorable`
`00c -US-Fiorina-Carly-Favorable`
`00c -US-Kasich-John-Favorable`
`00c -US-Perry-Rick-Favorable`
`00c -US-Carson-Ben-Favorable`
`00c -US-Warren-Elizabeth-Favorable`
`00c -US-Huckabee-Mike-Favorable`
`00c -US-Walker-Scott-Favorable`
`00c -US-Cuomo-Andrew-Favorable`
`00c -US-Santorum-Rick-Favorable`
`00c -US-Bush-Jeb-Favorable`
`00c -US-Paul-Rand-Favorable`
`00c -US-Christie-Chris-Favorable`
`00c -US-Pelosi-Nancy-Favorable`
`00c -US-Reid-Harry-Favorable`
`00c -US-McConnell-Mitch-Favorable`
`00c -US-Boehner-John-Favorable`
`00c -US-Biden-Joe-Favorable`
`00c -US-Ryan-Paul-Favorable`
`00c -US-Romney-Mitt-Favorable`

**Comment by adamhooper** [comment]
Fixed in commit 1867596
