### ISSUE TITLE
Data thats downloaded seems to be limited

### ISSUE THREAD

**Issue by dmadeka** [huffpostdata/python-pollster#4]
For example, for the general election polls, downloading all the data only yields five or six polls where Trump and Clinton are > 0. Is there a reason for this?

**Comment by adamhooper** [comment]
Hi there! Please provide some example code, the result `python-pollster` gives, and a description of what's wrong with that result.

**Comment by dmadeka** [comment]
So, I looked at the chart:

![image](https://cloud.githubusercontent.com/assets/7892382/18153664/05d66760-6fcd-11e6-9e6b-e3a53a1f3a22.png)

And tried to download the corresponding polls:

![image](https://cloud.githubusercontent.com/assets/7892382/18153681/146fae30-6fcd-11e6-864f-818b2dd9f131.png)

But, the number of non-trivial results seem to be very limited:

![image](https://cloud.githubusercontent.com/assets/7892382/18153688/2332b32c-6fcd-11e6-9118-244325fc36e6.png)

In fact, for significant polls there are barely 60:

![image](https://cloud.githubusercontent.com/assets/7892382/18153712/3c9a6d50-6fcd-11e6-96c0-365fa6a004f7.png)


Just wanted to make sure that made sense

**Comment by dmadeka** [comment]
Leads to sparse maps:

https://github.com/bloomberg/bqplot/pull/303

**Comment by adamhooper** [comment]
Thanks ... but what's the code you wrote to populate `data`?

**Comment by dmadeka** [comment]
For getting the data I used:

```python
raw_data = pollster.charts(topic='2016-president')
```

```python
def get_candidate_data(question):
    clinton, trump, undecided, other = 0., 0., 0., 0.
    for candidate in question['subpopulations'][0]['responses']:
        if candidate['choice'] == 'Hillary Clinton':
            clinton = candidate['value']
        elif candidate['choice'] == 'Donald Trump':
            trump = candidate['value']
        elif candidate['choice'] == 'Undecided':
            undecided = candidate['value']
        else:
            other = candidate['value']
    return clinton, trump, other, undecided

def get_row(question, partisan='Nonpartisan', end_date='2016-06-21'):
    if question['topic'] != '2016-president':
        return
    hillary, donald, other, undecided = get_candidate_data(question)
    return [{'Name': question['name'], 'Partisan': partisan, 'State': question['state'],
             'Date': np.datetime64(end_date), 'Trump': donald, 'Clinton': hillary, 'Other': other,
             'Undecided': undecided}]

def analyze_polls(polls):
    global data
    for poll in polls:
        for question in poll.questions:
            resp = get_row(question, partisan=poll.partisan, end_date=poll.end_date)
            if resp is not None:
                data = data.append(resp)
    return

```

```python
data = pd.DataFrame(columns=['Name', 'Partisan', 'State', 'Date', 'Trump', 'Clinton', 'Other',
                     'Undecided'])

for i in raw_data:
    analyze_polls(i.polls())
```

**Comment by adamhooper** [comment]
You're going poll-question by poll-question, but different poll questions have different response phrasings. For some polls, a `choice` might be `u'Hillary Clinton'`. For other polls, the `choice` could be u`'Clinton'`. Another would be `u'Hillary Clinton, the Democratic Candidate'`. Pollster doesn't control these: it just copy/pastes from the poll results. If there's a typo in the poll, there will be a typo in Pollster.

So here's a simple workaround: look for `last_name` of `u'Trump'` or `u'Clinton'`. That will work because `last_name` is a field that we at Pollster control.

We're totally on board with helping you use the API. But I don't consider this a bug in python-pollster, so I'll close this issue. I encourage you to join https://groups.google.com/forum/#!forum/pollster-users and discuss everything API-related.

**Comment by dmadeka** [comment]
That worked much better @adamhooper 

Thanks! Just a quick question, whats the license on the data?

**Comment by adamhooper** [comment]
CC-by-nc-sa , as per http://elections.huffingtonpost.com/pollster/api.

IANAL, but my understanding is: "by" is easy (please cite and link to us) and "sa" is easy (please publish derived CSVs -- which is good form, anyway). As for NC: I believe AOL considers public-interest news reporting (like NYT or 538 predictions/stories) to be "non-commercial". I don't know where the boundaries are to that definition. To be safe, please double-check with pollster-feedback@huffingtonpost.com.
