### ISSUE TITLE
(Python 3 support) Version 1.5.0 is not available on pypi

### ISSUE THREAD

**Issue by SylvainCorlay** [huffpostdata/python-pollster#7]
Pollster 1.5.0 is not available on pypi. Latest available version does not support Python 3.

> Currently, `python-pollster` does not work with Python 3. 

> - usage of urllib2
> - In Python 3, using `as` is required for catching exceptions.

**Comment by SylvainCorlay** [comment]
Closing, seems to be fixed in 1.5.0

**Comment by SylvainCorlay** [comment]
Actually 1.5.0 is not uploaded correctly to pypi.

**Comment by adamhooper** [comment]
Thank you for notifying me. I've uploaded a new version.
