### ISSUE TITLE
Behind proxy, 'get' methods do not work

### ISSUE THREAD

**Issue by wfspotz** [huffpostdata/python-pollster#9]
At work, my internet provider is behind a proxy server, and I cannot get any data from pollster. At home, I am not behind a proxy server, and pollster works fine. At work, I set the following environment variables to the appropriate server URL:

> `PROXY`
> `ALL_PROXY`
> `FTP_PROXY`
> `ftp_proxy`
> `HTTP_PROXY`
> `http_proxy`
> `HTTPS_PROXY`
> `https_proxy`
> `RSYNC_PROXY`

I have verified that this works with other communication protocols. For example, I can push or pull, to or from github if my environment variables are set at work, but can't if they are not set.

**Comment by adamhooper** [comment]
Thanks for spotting this! I'll get to it next week.

**Comment by adamhooper** [comment]
(If you're in a rush, I believe the hack is to edit https://github.com/huffpostdata/python-pollster/blob/master/pollster/rest.py#L77 -- change `self.pool_manager = urllib3.PoolManager(...)` to `import os; self.pool_manager = urllib3.proxy_from_url(os.getenv('HTTPS_PROXY'), ...)`. ... but I haven't tested this.)

**Comment by wfspotz** [comment]
OK, that worked. To get it to work whether HTTPS_PROXY is set or not, I used:

> `        import os`
> `        https_proxy = os.getenv('HTTPS_PROXY')`
> `        if https_proxy: ...`

and implement both the old and new `urllib3` calls.

**Comment by adamhooper** [comment]
@wfspotz Could you please whether the `https-proxy` branch works for you? The changes: https://github.com/huffpostdata/python-pollster/compare/https-proxy?expand=1#diff-1e5c0218bb57733b32d93658441a027f

**Comment by wfspotz** [comment]
Yes, it works for me. I am at work, so I can't check the non-proxy logic right now, but what you added looks functionally equivalent to quickie hack I used over the weekend.

**Comment by adamhooper** [comment]
Super! Thanks. I've already tested the non-proxy logic, and it works as well :). Will release new version.

**Comment by adamhooper** [comment]
Released v2.0.1.
